## <NAME>
## 
## DESCRIPTION
## 
## Rules
## -----
##

import os
import glob

ruleorder: convert > move

checkpoint unzip:
  input: "data/{identifier}.zip"
  output: 
    d=directory("data/{identifier}-unzipped"),
  shell: "mkdir {output} -p; unzip {input} -d {output.d}"

rule f:
  input: rules.unzip.output.d
  output: "data/{identifier}-unzipped/{name}.cif"

def get_input(wildcards):
  # we find the file in the data folder
  final_target = wildcards.identifier
  final_format = wildcards.ext
  files = os.listdir("data")
  match = [f for f in files if wildcards.identifier.startswith(f.split(".")[0])].pop()

  if match.endswith("zip"):
    unzip_ckp = checkpoints.unzip.get(identifier=match.replace(".zip", ""))
    final_target = f"{unzip_ckp.output[0]}/{wildcards.identifier}"
  else:
    final_target = f"data/{wildcards.identifier}"
  output = f"{final_target}.{final_format}"
  return output

rule move:
  input: get_input
  output: "results/input/{identifier}.{ext}"
  shell: "cp {input} {output}"


rule convert:
  conda: 'envs/comparison.yml'
  input: "results/input/{identifier}.cif"
  output: "results/input/{identifier}.pdb"
  shell: "python3 workflow/scripts/convert-cf-to-pdb.py {input} {output}"


## plip:
##    Run the plip programme on the input data-file to determine the protein
##    ligand interactions.
##
rule plip:
  # threads: 8
  container:
    "docker://pharmai/plip:2.3.0-multi"
  input:
    "results/input/{identifier}.pdb"
  output:
    directory("results/plip/{identifier}"),
  shell:
    """
    python3 /src/plip/plipcmd.py  -f {input} -o {output} -yvxtp
    """
## tm_align:
##    Run the TMalign programme.
##
rule tm_align:
  conda: 'envs/comparison.yml'
  input:
    x="target/{x}.{ext}",
    y="data/{y}.pdb"
  output: "results/metabolon-prediction/tm-scores/af3_enolase"
  shell: "TMalign {input.x} {input.y} > {output}"

## help:
##    Show the help.
##
rule help:
  input: "workflow/Snakefile"
  shell: "sed -n 's/^##//p' {input}"

## clean:
##    Clean all outputs from the results folder.
##
rule clean:
  shell: "rm -rf results/*"

## build_overview:
##    Print the directed acyclic graph.
##
rule build_overview:
  output:
    "results/method.{fileformat}"
  shell:
    """
    snakemake -c 1 --forceall --dag | dot -T{wildcards.fileformat} > {output}
    """

rule install_easy_graph:
  conda:
    "envs/utils.yml"
  output:
    touch("results/checkpoints/install_easy_graph")
  shell:
    """
    echo "Installing easy graph"
    cpan -i App::cpanminus
    cpanm Graph::Easy
    """

## build_overview_ascii:
##    Prints the graph in ascii format.
rule build_ascii_graph:
  conda:
    "envs/utils.yml"
  input:
    "results/checkpoints/install_easy_graph"
  output:
    "results/method-simple.ascii"
  shell:
    """
    snakemake -c 1 --forceall --dag > out
    graph-easy --from=dot --as_ascii out >  {output}
    rm out
    """
